// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKkEMvc7GcKZGP_vPjeeDlMnFt8_V4P8',
    appId: '1:1072964588806:web:507f4dd59a1654fdef3a87',
    messagingSenderId: '1072964588806',
    projectId: 'easybot-flutter',
    authDomain: 'easybot-flutter.firebaseapp.com',
    storageBucket: 'easybot-flutter.firebasestorage.app',
    measurementId: 'G-PNE6XCDGBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvO3aJjjWdYLV4xVD1DPaLzRNp2uiT5O4',
    appId: '1:1072964588806:android:99a7c6a8dcf77d66ef3a87',
    messagingSenderId: '1072964588806',
    projectId: 'easybot-flutter',
    storageBucket: 'easybot-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0zUQ0XHfySiOdMChqB1RgZR5W4zAQ-ac',
    appId: '1:1072964588806:ios:5664e3d3353afb9aef3a87',
    messagingSenderId: '1072964588806',
    projectId: 'easybot-flutter',
    storageBucket: 'easybot-flutter.firebasestorage.app',
    iosBundleId: 'com.eazybot.eazybot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0zUQ0XHfySiOdMChqB1RgZR5W4zAQ-ac',
    appId: '1:1072964588806:ios:5664e3d3353afb9aef3a87',
    messagingSenderId: '1072964588806',
    projectId: 'easybot-flutter',
    storageBucket: 'easybot-flutter.firebasestorage.app',
    iosBundleId: 'com.eazybot.eazybot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtKkEMvc7GcKZGP_vPjeeDlMnFt8_V4P8',
    appId: '1:1072964588806:web:43eef3ba80a46a3bef3a87',
    messagingSenderId: '1072964588806',
    projectId: 'easybot-flutter',
    authDomain: 'easybot-flutter.firebaseapp.com',
    storageBucket: 'easybot-flutter.firebasestorage.app',
    measurementId: 'G-KHLMCZ546R',
  );
}
