// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBajWz0FTfylRSiYjtFMTNlg8YEbbErEG8',
    appId: '1:984583576200:web:60183b84f5e8918aafdd3d',
    messagingSenderId: '984583576200',
    projectId: 'fir-5a376',
    authDomain: 'fir-5a376.firebaseapp.com',
    storageBucket: 'fir-5a376.firebasestorage.app',
    measurementId: 'G-J97RZTG5EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdS0NpswRX2ddl_jqpSYHDkD278BemnoM',
    appId: '1:984583576200:android:dc1e2289d68eb90eafdd3d',
    messagingSenderId: '984583576200',
    projectId: 'fir-5a376',
    storageBucket: 'fir-5a376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2JvK4lm-bWe1OJ83sYC0IGNWKjUQSjY',
    appId: '1:984583576200:ios:6e06286b9ff76d90afdd3d',
    messagingSenderId: '984583576200',
    projectId: 'fir-5a376',
    storageBucket: 'fir-5a376.firebasestorage.app',
    iosBundleId: 'com.eazybot.eazybot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2JvK4lm-bWe1OJ83sYC0IGNWKjUQSjY',
    appId: '1:984583576200:ios:6e06286b9ff76d90afdd3d',
    messagingSenderId: '984583576200',
    projectId: 'fir-5a376',
    storageBucket: 'fir-5a376.firebasestorage.app',
    iosBundleId: 'com.eazybot.eazybot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQajl199VwhY_plmovgjpO48IhwpbRk9I',
    appId: '1:984583576200:web:8daef51ee4ccf079afdd3d',
    messagingSenderId: '984583576200',
    projectId: 'fir-5a376',
    authDomain: 'fir-5a376.firebaseapp.com',
    storageBucket: 'fir-5a376.firebasestorage.app',
    measurementId: 'G-ZCGCQ36035',
  );

}